FROM python:3.7
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN apt-get update
RUN apt install -y netcat
RUN mkdir /app
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ./entrypoint.prod.sh /app/entrypoint.prod.sh
COPY . /app/
ENTRYPOINT [ "/app/entrypoint.prod.sh" ]